{% set name = "mplhep_data" %}
{% set version = "0.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b54d257f3f53c93a442cda7a6681ce267277e09173c0b41fd78820f78321772f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7

test:
  imports:
    - mplhep_data

about:
  home: https://github.com/scikit-hep/mplhep_data
  license: MIT AND OFL-1.1 AND LPPL-1.3c
  license_file:
    - LICENSE
    - src/mplhep_data/fonts/firasans/LICENSE_FiraSans
    - src/mplhep_data/fonts/firamath/LICENSE_FiraMath
    - src/mplhep_data/fonts/texgyreheros/LICENSE_TexGyreHeros
  summary: Data sub-package for mplhep
  dev_url: https://github.com/scikit-hep/mplhep_data

extra:
  recipe-maintainers:
    - andrzejnovak
    - chrisburr
